<?php

namespace Database\Seeders;

use App\Models\ExplosionExample;
use Illuminate\Database\Seeder;

class ExplosionExampleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $explosionExample = [
            [
                'operation' => 'Manhattan Project',
                'code_name' => 'Trinity',
                'device'    => 'Gadget',
                'country'   => 'United States',
                'test_site' => 'Trinity Site, New Mexico',
                'date'      => 'July 16, 1945',
                'test_type' => 'Atmospheric',
                'power'     =>  25,
                'url' => 'Trinity.jpg',
            ],
            [
                'operation' => 'Manhattan Project',
                'code_name' => '',
                'device'    => 'Little Boy',
                'country'   => 'Japan',
                'test_site' => 'Hiroshima ',
                'date'      => '6 August 1945',
                'test_type' => 'Atmospheric',
                'power'     =>  15,
                'url' => 'Little_Boy.jpg',
            ],
            [
                'operation' => 'Manhattan Project',
                'code_name' => '',
                'device'    => 'Mk III "Fat Man"',
                'country'   => 'Japan',
                'test_site' => 'Nagasaki ',
                'date'      => '9 August 1945',
                'test_type' => 'Atmospheric',
                'power'     =>  21,
                'url' => 'Fat_Man.jpg',
            ],
            [
                'operation' => 'Crossroads',
                'code_name' => 'Able',
                'device'    => 'Mk III "Gilda"',
                'country'   => 'United States',
                'test_site' => 'NE Lagoon, Bikini Atoll',
                'date'      => 'June 30, 1946     ',
                'test_type' => 'Atmospheric',
                'power'     =>  22,
                'url' => 'Crossroads_Able.jpg',
            ],
            [
                'operation' => 'Crossroads',
                'code_name' => 'Baker',
                'device'    => 'Mk III "Helen of Bikini"',
                'country'   => 'United States',
                'test_site' => 'NE Lagoon, Bikini Atoll',
                'date'      => 'July 24, 1946',
                'test_type' => 'Underwater',
                'power'     =>  23,
                'url' => 'Crossroads_Baker.jpg',
            ],
            [
                'operation' => 'Sandstone',
                'code_name' => 'X-ray',
                'device'    => 'Mk-3, Type B levitated',
                'country'   => 'United States',
                'test_site' => 'Enjebi (Janet), Enewetak Atoll',
                'date'      => 'April 14, 1948',
                'test_type' => 'Atmospheric',
                'power'     =>  37,
                'url' => 'Sandstone_X-ray.png',
            ],
            [
                'operation' => 'Sandstone',
                'code_name' => 'Yoke',
                'device'    => 'Mk-3, Type B levitated',
                'country'   => 'United States',
                'test_site' => 'Aomon (Sally), Enewetak Atoll',
                'date'      => 'April 30, 1948',
                'test_type' => 'Atmospheric',
                'power'     =>  49,
                'url' => 'Sandstone_Yoke.jpg',
            ],
            [
                'operation' => 'Sandstone',
                'code_name' => 'Zebra',
                'device'    => 'Mk-3, Type B levitated',
                'country'   => 'United States',
                'test_site' => 'Runit (Yvonne), Enewetak Atoll',
                'date'      => 'May 14, 1948',
                'test_type' => 'Atmospheric',
                'power'     =>  18,
                'url' => 'Sandstone_Zebra.jpg',
            ],
            [
                'operation' => 'Ranger',
                'code_name' => 'Able',
                'device'    => 'Mk-4, Type D',
                'country'   => 'United States',
                'test_site' => 'Nevada Test Site Area 5',
                'date'      => 'January 27, 1951',
                'test_type' => 'Atmospheric',
                'power'     =>  1,
                'url' => 'default.jpg',
            ],
            [
                'operation' => 'Ranger',
                'code_name' => 'Baker',
                'device'    => 'Mk-4, Type D, TOM Init',
                'country'   => 'United States',
                'test_site' => 'Nevada Test Site Area 5',
                'date'      => 'January 28, 1951',
                'test_type' => 'Atmospheric',
                'power'     =>  8,
                'url' => 'default.jpg',
            ],
            [
                'operation' => 'Ranger',
                'code_name' => 'Easy',
                'device'    => 'Mk-4, Type D',
                'country'   => 'United States',
                'test_site' => 'Nevada Test Site Area 5',
                'date'      => 'February 1, 1951',
                'test_type' => 'Atmospheric',
                'power'     =>  1,
                'url' => 'default.jpg',
            ],
            [
                'operation' => 'Ranger',
                'code_name' => 'Baker 2',
                'device'    => 'Mk-4, Type D',
                'country'   => 'United States',
                'test_site' => 'Nevada Test Site Area 5',
                'date'      => 'February 2, 1951',
                'test_type' => 'Atmospheric',
                'power'     =>  8,
                'url' => 'default.jpg',
            ],
            [
                'operation' => 'Ranger',
                'code_name' => 'Fox',
                'device'    => 'Mk-6 HOW, Type D "Freddy"',
                'country'   => 'United States',
                'test_site' => 'Nevada Test Site Area 5',
                'date'      => 'February 6, 1951',
                'test_type' => 'Atmospheric',
                'power'     =>  22,
                'url' => 'Ranger_Fox.jpg',
            ],
            [
                'operation' => 'Greenhouse',
                'code_name' => 'Dog',
                'device'    => 'Mk-6D',
                'country'   => 'United States',
                'test_site' => 'Runit (Yvonne), Enewetak Atoll',
                'date'      => 'April 7, 1951',
                'test_type' => 'Atmospheric',
                'power'     =>  81,
                'url' => 'Greenhouse_Dog.jpg',
            ],
            [
                'operation' => 'Greenhouse',
                'code_name' => 'Easy',
                'device'    => 'TX-5D',
                'country'   => 'United States',
                'test_site' => 'Enjebi (Janet), Enewetak Atoll',
                'date'      => 'April 20, 1951',
                'test_type' => 'Atmospheric',
                'power'     =>  47,
                'url' => 'default.jpg',
            ],
            [
                'operation' => 'Greenhouse',
                'code_name' => 'George',
                'device'    => 'Cylinder',
                'country'   => 'United States',
                'test_site' => 'Ebiriru (Ruby), Enewetak Atoll',
                'date'      => 'May 8, 1951',
                'test_type' => 'Atmospheric',
                'power'     =>  225,
                'url' => 'Greenhouse_George.jpg',
            ],
            [
                'operation' => 'Greenhouse',
                'code_name' => 'Item',
                'device'    => 'Booster',
                'country'   => 'United States',
                'test_site' => 'Enjebi (Janet), Enewetak Atoll',
                'date'      => 'May 24, 1951',
                'test_type' => 'Atmospheric',
                'power'     =>  45.5,
                'url' => 'default.jpg',
            ],
            [
                'operation' => 'Buster–Jangle',
                'code_name' => 'Able',
                'device'    => 'Mk-6 "Petite Plutonium"',
                'country'   => 'United States',
                'test_site' => 'Nevada Test Site Area 7',
                'date'      => 'October 22, 1951',
                'test_type' => 'Atmospheric',
                'power'     =>  0,
                'url' => 'default.jpg',
            ],
            [
                'operation' => 'Buster–Jangle',
                'code_name' => 'Baker',
                'device'    => 'Mk-4 "LT"',
                'country'   => 'United States',
                'test_site' => 'Nevada Test Site Area 7',
                'date'      => 'October 28, 1951',
                'test_type' => 'Atmospheric',
                'power'     =>  3.5,
                'url' => 'default.jpg',
            ],
            [
                'operation' => 'Buster–Jangle',
                'code_name' => 'Charlie',
                'device'    => 'Mk-4 "PC"',
                'country'   => 'United States',
                'test_site' => 'Nevada Test Site Area 7',
                'date'      => 'October 30, 1951',
                'test_type' => 'Atmospheric',
                'power'     =>  14,
                'url' => 'Buster_Charlie.jpg',
            ],
            [
                'operation' => 'Buster–Jangle',
                'code_name' => 'Dog',
                'device'    => 'Mk-4 "NF"',
                'country'   => 'United States',
                'test_site' => 'Nevada Test Site Area 7',
                'date'      => 'November 1, 1951',
                'test_type' => 'Atmospheric',
                'power'     =>  21,
                'url' => 'Buster_Dog.jpg',
            ],
            [
                'operation' => 'Buster–Jangle',
                'code_name' => 'Easy',
                'device'    => 'TX-7E',
                'country'   => 'United States',
                'test_site' => 'Nevada Test Site Area 7',
                'date'      => 'November 5, 1951',
                'test_type' => 'Atmospheric',
                'power'     =>  31,
                'url' => 'Buster_Easy.jpg',
            ],
            [
                'operation' => 'Buster–Jangle',
                'code_name' => 'Sugar',
                'device'    => 'Mk-6 "Johnny"',
                'country'   => 'United States',
                'test_site' => 'Nevada Test Site Area 9',
                'date'      => 'November 19, 1951',
                'test_type' => 'Atmospheric',
                'power'     =>  1.2,
                'url' => 'Jangle_Sugar.jpg',
            ],
            [
                'operation' => 'Buster–Jangle',
                'code_name' => 'Uncle',
                'device'    => 'Mk-6 "Frankie"',
                'country'   => 'United States',
                'test_site' => 'Nevada Test Site Area 10',
                'date'      => 'November 29, 1951',
                'test_type' => 'Atmospheric',
                'power'     =>  1.2,
                'url' => 'Jangle_Uncle.jpg',
            ],
            [
                'operation' => 'Tumbler–Snapper',
                'code_name' => 'Able',
                'device'    => 'Mk-4',
                'country'   => 'United States',
                'test_site' => 'Nevada Test Site Area 5',
                'date'      => 'April 1, 1952',
                'test_type' => 'Atmospheric',
                'power'     =>  1,
                'url' => 'Tumbler_Able.jpg',
            ],
            [
                'operation' => 'Tumbler–Snapper',
                'code_name' => 'Baker',
                'device'    => 'Mk-4',
                'country'   => 'United States',
                'test_site' => 'Nevada Test Site Area 7',
                'date'      => 'April 15, 1952',
                'test_type' => 'Atmospheric',
                'power'     =>  1,
                'url' => 'default.jpg',
            ],
            [
                'operation' => 'Tumbler–Snapper',
                'code_name' => 'Charlie',
                'device'    => 'Mk-4',
                'country'   => 'United States',
                'test_site' => 'Nevada Test Site Area 7',
                'date'      => 'April 22, 1952',
                'test_type' => 'Atmospheric',
                'power'     =>  31,
                'url' => 'Tumbler_Charlie.jpg',
            ],
            [
                'operation' => 'Tumbler–Snapper',
                'code_name' => 'Dog',
                'device'    => 'TX-7',
                'country'   => 'United States',
                'test_site' => 'Nevada Test Site Area 7',
                'date'      => 'May 1, 1952',
                'test_type' => 'Atmospheric',
                'power'     =>  19,
                'url' => 'Snapper_Dog.jpg',
            ],
            [
                'operation' => 'Tumbler–Snapper',
                'code_name' => 'Easy',
                'device'    => 'Mk-12 "BROK-1"',
                'country'   => 'United States',
                'test_site' => 'Nevada Test Site Area 1',
                'date'      => 'May 7, 1952',
                'test_type' => 'Atmospheric',
                'power'     =>  12,
                'url' => 'default.jpg',
            ],
            [
                'operation' => 'Tumbler–Snapper',
                'code_name' => 'Fox',
                'device'    => 'TX-5 "XR1"',
                'country'   => 'United States',
                'test_site' => 'Nevada Test Site Area 4',
                'date'      => 'May 25, 1952',
                'test_type' => 'Atmospheric',
                'power'     =>  11,
                'url' => 'Snapper_Fox.jpg',
            ],
            [
                'operation' => 'Tumbler–Snapper',
                'code_name' => 'George',
                'device'    => 'TX-5 "XR-2"',
                'country'   => 'United States',
                'test_site' => 'Nevada Test Site Area 3',
                'date'      => 'June 1, 1952',
                'test_type' => 'Atmospheric',
                'power'     =>  15,
                'url' => 'default.jpg',
            ],
            [
                'operation' => 'Tumbler–Snapper',
                'code_name' => 'How',
                'device'    => 'TX-12 "Scorpion"',
                'country'   => 'United States',
                'test_site' => 'Nevada Test Site Area 2',
                'date'      => 'June 5, 1952',
                'test_type' => 'Atmospheric',
                'power'     =>  14,
                'url' => 'Snapper_How.jpg',
            ],
            [
                'operation' => 'Upshot–Knothole',
                'code_name' => 'Annie',
                'device'    => 'TX-5HE "XR-3" Type D pit',
                'country'   => 'United States',
                'test_site' => 'Nevada Test Site Area 3',
                'date'      => 'March 17, 1953',
                'test_type' => 'Atmospheric',
                'power'     =>  16,
                'url' => 'Upshot–Knothole_Annie.jpg',
            ],
            [
                'operation' => 'Upshot–Knothole',
                'code_name' => 'Nancy',
                'device'    => 'TX-14 "Nevada Zombie"',
                'country'   => 'United States',
                'test_site' => 'Nevada Test Site Area 4',
                'date'      => 'March 24, 1953',
                'test_type' => 'Atmospheric',
                'power'     =>  24,
                'url' => 'Upshot–Knothole_Nancy.jpg',
            ],
            [
                'operation' => 'Upshot–Knothole',
                'code_name' => 'Ruth',
                'device'    => 'MK-6 "Hydride I"',
                'country'   => 'United States',
                'test_site' => 'Nevada Test Site Area 7',
                'date'      => 'March 31, 1953',
                'test_type' => 'Atmospheric',
                'power'     =>  0.2,
                'url' => 'default.jpg',
            ],
            [
                'operation' => 'Upshot–Knothole',
                'code_name' => 'Dixie',
                'device'    => 'MK-5D "DD-1"',
                'country'   => 'United States',
                'test_site' => 'Nevada Test Site Area 7',
                'date'      => 'April 6, 1953',
                'test_type' => 'Atmospheric',
                'power'     =>  11,
                'url' => 'default.jpg',
            ],
            [
                'operation' => 'Upshot–Knothole',
                'code_name' => 'Ray',
                'device'    => 'MK-6 "Hydride II"',
                'country'   => 'United States',
                'test_site' => 'Nevada Test Site Area 4',
                'date'      => 'April 11, 1953',
                'test_type' => 'Atmospheric',
                'power'     =>  0.22,
                'url' => 'default.jpg',
            ],
            [
                'operation' => 'Upshot–Knothole',
                'code_name' => 'Badger',
                'device'    => 'TX-16 "Buzzard"',
                'country'   => 'United States',
                'test_site' => 'Nevada Test Site Area 2',
                'date'      => 'April 18, 1953',
                'test_type' => 'Atmospheric',
                'power'     =>  23,
                'url' => 'Upshot–Knothole_Badger.jpg',
            ],
            [
                'operation' => 'Upshot–Knothole',
                'code_name' => 'Simon',
                'device'    => 'TX-17/24 "Simultaneity"',
                'country'   => 'United States',
                'test_site' => 'Nevada Test Site Area 1',
                'date'      => 'April 25, 1953',
                'test_type' => 'Atmospheric',
                'power'     =>  43,
                'url' => 'Upshot–Knothole_Simon.jpg',
            ],
            [
                'operation' => 'Upshot–Knothole',
                'code_name' => 'Encore',
                'device'    => 'MK-6D',
                'country'   => 'United States',
                'test_site' => 'Nevada Test Site Area 5',
                'date'      => 'May 8, 1953',
                'test_type' => 'Atmospheric',
                'power'     =>  27,
                'url' => 'default.jpg',
            ],
            [
                'operation' => 'Upshot–Knothole',
                'code_name' => 'Harry',
                'device'    => 'TX-13D "Hamlet"',
                'country'   => 'United States',
                'test_site' => 'Nevada Test Site Area 3',
                'date'      => 'May 19, 1953',
                'test_type' => 'Atmospheric',
                'power'     =>  32,
                'url' => 'Upshot–Knothole_Harry.jpg',
            ],
            [
                'operation' => 'Upshot–Knothole',
                'code_name' => 'Grable',
                'device'    => 'W9 (nuclear warhead) AFAP "Gun"',
                'country'   => 'United States',
                'test_site' => 'Nevada Test Site Area 5',
                'date'      => 'May 25, 1953',
                'test_type' => 'Atmospheric',
                'power'     =>  15,
                'url' => 'Upshot–Knothole_Grable.jpg',
            ],
            [
                'operation' => 'Upshot–Knothole',
                'code_name' => 'Climax',
                'device'    => 'MK-7, "Cobra", Type D pit',
                'country'   => 'United States',
                'test_site' => 'Nevada Test Site Area 7',
                'date'      => 'June 4, 1953',
                'test_type' => 'Atmospheric',
                'power'     =>  61,
                'url' => 'Upshot–Knothole_Climax.jpg',
            ],
            [
                'operation' => 'Ivy',
                'code_name' => 'Mike',
                'device'    => '"Sausage" w/ TX-5 primary',
                'country'   => 'United States',
                'test_site' => 'Elugelab (Flora), Enewetak Atoll',
                'date'      => 'October 31, 1952',
                'test_type' => 'Atmospheric',
                'power'     =>  10400,
                'url' => 'Ivy_Mike.jpg',
            ],
            [
                'operation' => 'Ivy',
                'code_name' => 'King',
                'device'    => 'Mk-18F SOB',
                'country'   => 'United States',
                'test_site' => 'Runit (Yvonne), Enewetak Atoll',
                'date'      => 'November 15, 1952',
                'test_type' => 'Atmospheric',
                'power'     =>  540,
                'url' => 'Ivy_King.jpg',
            ],
            [
                'operation' => 'Castle',
                'code_name' => 'Bravo',
                'device'    => 'TX-21 "Shrimp"',
                'country'   => 'United States',
                'test_site' => 'Namu (Charlie), Bikini Atoll',
                'date'      => 'February 28, 1954',
                'test_type' => 'Atmospheric',
                'power'     =>  15000,
                'url' => 'Castle_Bravo.jpg',
            ],
            [
                'operation' => 'Castle',
                'code_name' => 'Romeo',
                'device'    => 'TX/EC-17A "Runt"',
                'country'   => 'United States',
                'test_site' => 'Yurochi aka Irioj (Dog), Bikini Atoll',
                'date'      => 'March 26, 1954',
                'test_type' => 'Atmospheric',
                'power'     =>  11000,
                'url' => 'Castle_Romeo.jpg',
            ],
            [
                'operation' => 'Castle',
                'code_name' => 'Koon',
                'device'    => 'Morgenstern',
                'country'   => 'United States',
                'test_site' => 'Eninmen (Tare), Bikini Atoll',
                'date'      => 'April 6, 1954',
                'test_type' => 'Atmospheric',
                'power'     =>  110,
                'url' => 'default.jpg',
            ],
            [
                'operation' => 'Castle',
                'code_name' => 'Union',
                'device'    => 'TX-14 w/ RACER IV "Alarm Clock"',
                'country'   => 'United States',
                'test_site' => 'Yurochi aka Irioj (Dog), Bikini Atoll',
                'date'      => 'April 25, 1954',
                'test_type' => 'Atmospheric',
                'power'     =>  69000,
                'url' => 'Castle_Union.jpg',
            ],
            [
                'operation' => 'Castle',
                'code_name' => 'Yankee 2',
                'device'    => 'TX/EC-24 RACER IV "Runt II"',
                'country'   => 'United States',
                'test_site' => 'Yurochi aka Irioj (Dog), Bikini Atoll',
                'date'      => 'May 4, 1954',
                'test_type' => 'Atmospheric',
                'power'     =>  13500,
                'url' => 'default.jpg',
            ],
            [
                'operation' => 'Castle',
                'code_name' => 'Nectar',
                'device'    => 'TX-15 COBRA "Zombie"',
                'country'   => 'United States',
                'test_site' => 'Elugelab (Flora), Enewetak Atoll',
                'date'      => 'May 13, 1954',
                'test_type' => 'Atmospheric',
                'power'     =>  1700,
                'url' => 'default.jpg',
            ],
        ];

        ExplosionExample::query()->insert($explosionExample);
    }
}

